name: test
on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      -run: make setup
   test:
     runs-on: ubuntu-latest
     steps:
      -run: make test
    lint:
      runs-on: ubuntu-latest
      steps:
        -run: make lint
